kind: Namespace
apiVersion: v1
metadata:
  name: alb-ingres-controller-demo
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: alb-ingres-controller-demo
  labels:
    app: redis
spec:
  replicas: 1
  serviceName: redis
  selector:
    matchLabels:
      app: redis
  template: # Pod template
    metadata:
      labels:
        app: redis
    spec: 
      volumes:
        - name: redis-data
          hostPath:
            path: /opt/redis-data # path on the host where the data will be stored
            type: DirectoryOrCreate  # create the directory if it does not exist
      containers:
        - name: redis
          image: redis:6.2
          ports:
            - containerPort: 6379
              name: redis
          resources:
            limits:
              cpu: 150m
              memory: 150Mi
          volumeMounts:
            - mountPath: /data # mount the volume to the container
              name: redis-data # name of the volume defined above
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: alb-ingres-controller-demo
  labels:
    app: redis
spec:
  ports:
    - name: redis
      port: 6379
      targetPort: redis
  selector:
    app: redis
  type: ClusterIP # default type is ClusterIP, but you can change it to NodePort or LoadBalancer if needed
  sessionAffinity: None # default is None, but you can change it to ClientIP if needed
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: alb-ingres-controller-demo
data:
  REDIS_HOST: redis.alb-ingres-controller-demo.svc
  REDIS_PORT: "6379"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: participate
  namespace: alb-ingres-controller-demo
  labels:
    app: participate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: participate
  template:
    metadata:
      labels:
        app: participate
    spec: 
      containers:
        - name: participate
          image: ghcr.io/kul-samples/thinknyx-participate-app:latest
          ports:
            - containerPort: 5000
              name: participate
          envFrom:
            - configMapRef:
                name: redis-config
---
apiVersion: v1
kind: Service
metadata:
  name: participate
  namespace: alb-ingres-controller-demo
  labels:
    app: participate
spec:
  type: ClusterIP
  ports:
    - name: participate
      port: 80
      targetPort: participate
  selector:
    app: participate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: submissions
  namespace: alb-ingres-controller-demo
  labels:
    app: submissions
spec:
  replicas: 1
  selector:
    matchLabels:
      app: submissions
  template:
    metadata:
      labels:
        app: submissions
    spec: 
      containers:
        - name: submissions
          image: ghcr.io/kul-samples/thinknyx-submissions-app:latest
          ports:
            - containerPort: 5000
              name: submissions
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
          envFrom:
            - configMapRef:
                name: redis-config
---
apiVersion: v1
kind: Service
metadata:
  name: submissions
  namespace: alb-ingres-controller-demo
  labels:
    app: submissions
spec:
  type: ClusterIP
  ports:
    - name: submissions
      port: 80
      targetPort: submissions
  selector:
    app: submissions
