apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: welcomeapp
  name: welcomeapp
  namespace: demo-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: welcomeapp
  template:
    metadata:
      labels:
        app: welcomeapp
    spec:
      containers:
      - image: ghcr.io/kul-samples/javawelcomeapp:v3
        name: javawelcomeapp
        resources:
          requests:
            cpu: 250m
            memory: 250Mi
          limits:
            cpu: 500m
            memory: 500Mi
        ports:
          - name: tomcat
            containerPort: 8080
